version: '3.9'

services:

  db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank-app
#      PGDATA: /var/lib/postgresql
    volumes:
      - psqldata:/var/lib/postgresql
    ports:
      - 5435:5432
    container_name: mono_bank

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  psqldata: